version: "3"
services:
  dns-server:
    image: vincent0700/dnsmasq
    container_name: dnsmasq
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf:/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
