version: "3"
services:
  dns-server:
    build: .
    image: vincent/dnsmasq:0.0.1
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf:/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"